### ISSUE TITLE
Finish consultation entry option

### ISSUE THREAD

**Issue by caseywilliams** [Gilmore-PDX-CS/Group3#1]
In the controller, there is a `CreateConsultation` method. This method will add a consultation right now, but it needs to write the consultation to a file, and it needs to print the resulting info on the screen for the user before returning to the main menu.

**Comment by Liriaene** [comment]
Okay I will work on that.
I have an observation though. We never established how we want files to be formatted so I am going to do

*top of file*
Member Name
Provider Name
Service Requested
Service Cost

**Comment by Liriaene** [comment]
Writing to file has been, at least to my knowledge, implemented. However, I am unsure if the file directory I used will work. I tested the functionality on my own desktop, but I do not know if a web address will work the same way. I will leave this issue open until it has been confirmed that it works.

**Comment by joel-lilja** [comment]
I fixed the  createConsultation method. Its now fully implemented with a working date and time. THE format in the file is correct and i fixed the issues with the file name throwing expections due to / / characters in the date and === characters in the member. 

previously it was trying to dump the entire member info into the filename where we only wanted the name.
